-- ============================================================================
-- UK Hotel Management — Schema Creation
-- ============================================================================
-- Source: "MySQL Constraints and Joins — UK Hotel Management Handbook",
-- Section 2.12 "Recommended complete schema". The four CREATE TABLE
-- statements below are reproduced verbatim from that section, including the
-- exact constraint names, the ON UPDATE CASCADE / ON DELETE RESTRICT choice
-- on both foreign keys, and the deliberate decision to make room_id a plain
-- INT PRIMARY KEY (not AUTO_INCREMENT) while guest_id and booking_id are
-- AUTO_INCREMENT. The stay_options table is added afterwards for the
-- CROSS JOIN pricing-grid demonstrations introduced in Section 8.3.
--
-- Verified against a live MySQL 8.0.46 instance.
-- ============================================================================

DROP DATABASE IF EXISTS uk_hotel_management;

CREATE DATABASE uk_hotel_management;
USE uk_hotel_management;

-- ----------------------------------------------------------------------------
-- Table 1: guest
-- ----------------------------------------------------------------------------
-- guest_email and guest_phone_number are each UNIQUE on their own (not a
-- composite UNIQUE). Per MySQL's documented UNIQUE behaviour, a UNIQUE
-- column may still hold multiple NULLs, because NULL is never considered
-- equal to another NULL for uniqueness purposes -- this is exploited
-- deliberately in 02_data_insertion.sql for guests who did not supply a
-- phone number.
-- ----------------------------------------------------------------------------
CREATE TABLE guest (
    guest_id INT AUTO_INCREMENT PRIMARY KEY,
    guest_name VARCHAR(100) NOT NULL,
    guest_age INT NOT NULL,
    guest_email VARCHAR(150) NOT NULL,
    guest_phone_number VARCHAR(20),
    guest_city VARCHAR(100) NOT NULL,
    CONSTRAINT uq_guest_email UNIQUE (guest_email),
    CONSTRAINT uq_guest_phone UNIQUE (guest_phone_number),
    CONSTRAINT chk_guest_age CHECK (guest_age BETWEEN 18 AND 120)
) ENGINE = InnoDB;

-- ----------------------------------------------------------------------------
-- Table 2: room
-- ----------------------------------------------------------------------------
-- room_id is a plain PRIMARY KEY, not AUTO_INCREMENT: physical room numbers
-- are assigned by the hotel (e.g. room 101, 205), not generated by the
-- database, so the handbook's schema treats them as externally-supplied
-- identifiers rather than surrogate keys.
-- ----------------------------------------------------------------------------
CREATE TABLE room (
    room_id INT PRIMARY KEY,
    room_type VARCHAR(50) NOT NULL,
    room_base_price DECIMAL(10,2) NOT NULL,
    room_status VARCHAR(30) NOT NULL DEFAULT 'Available',
    CONSTRAINT chk_room_price CHECK (room_base_price > 0),
    CONSTRAINT chk_room_status CHECK
        (room_status IN ('Available', 'Reserved', 'Occupied',
                         'Cleaning', 'Maintenance'))
) ENGINE = InnoDB;

-- ----------------------------------------------------------------------------
-- Table 3: bookings
-- ----------------------------------------------------------------------------
-- Both foreign keys use ON UPDATE CASCADE ON DELETE RESTRICT: if a guest_id
-- or room_id is ever renumbered, dependent bookings follow automatically
-- (CASCADE), but a guest or room cannot be deleted while bookings still
-- reference it (RESTRICT) -- deleting the booking history first is a
-- deliberate, auditable step, not an accidental side-effect of removing a
-- guest or room record. See 04_referential_integrity_demos.sql for both
-- behaviours proven live.
-- ----------------------------------------------------------------------------
CREATE TABLE bookings (
    booking_id INT AUTO_INCREMENT PRIMARY KEY,
    guest_id INT NOT NULL,
    room_id INT NOT NULL,
    booking_amount DECIMAL(10,2) NOT NULL,
    number_of_guests INT NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    CONSTRAINT chk_booking_amount CHECK (booking_amount > 0),
    CONSTRAINT chk_booking_guests CHECK (number_of_guests BETWEEN 1 AND 6),
    CONSTRAINT chk_booking_dates CHECK (check_out_date > check_in_date),
    CONSTRAINT fk_bookings_guest FOREIGN KEY (guest_id)
        REFERENCES guest(guest_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id)
        REFERENCES room(room_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE = InnoDB;

-- ----------------------------------------------------------------------------
-- Table 4: stay_options
-- ----------------------------------------------------------------------------
-- Introduced in Section 8.3 purely as a small reference table so that a
-- CROSS JOIN against `room` can build a full nights x price pricing grid
-- (see Query 17 in 05_join_queries.sql). It has no foreign keys into the
-- rest of the schema -- it is a standalone lookup table by design.
-- ----------------------------------------------------------------------------
CREATE TABLE stay_options (
    number_of_nights INT PRIMARY KEY
);

-- ----------------------------------------------------------------------------
-- Table creation order and why it is safe
-- ----------------------------------------------------------------------------
-- guest and room have no foreign keys, so either can be created first.
-- bookings must be created last because it references both of them.
-- stay_options has no dependency on any other table.
-- This matches the order the statements appear in above:
--   1. guest
--   2. room
--   3. bookings   (depends on guest, room)
--   4. stay_options
-- ============================================================================
